### ISSUE TITLE
UNable to uninstall

### ISSUE THREAD

**Issue by wailingduck** [Yaekith/Cordware#4]
Exception: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path)
   at CordwareNoGUIInjector.Program.Main(String[] args)
Make an issue with this on the github.

**Comment by ThonkPT** [comment]
close discord fully before uninstalling smh
